numero = int(input("ingrese un numero: "))
print("La tabla de multiplicar del numero ingresado es: ")
print(numero * 0)
print(numero * 1)
print(numero * 2)
print(numero * 3)
print(numero * 4)
print(numero * 5)
print(numero * 6)
print(numero * 7)
print(numero * 8)
print(numero * 9)
print(numero * 10)